/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mathlibra_Mathlibra */

#ifndef _Included_mathlibra_Mathlibra
#define _Included_mathlibra_Mathlibra
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mathlibra_Mathlibra
 * Method:    initNativeComponents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mathlibra_Mathlibra_initNativeComponents
  (JNIEnv *, jclass);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    createInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mathlibra_Mathlibra_createInstance
  (JNIEnv *, jclass);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    freeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mathlibra_Mathlibra_freeInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    setArg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mathlibra_Mathlibra_setArg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    interpretArg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mathlibra_Mathlibra_interpretArg
  (JNIEnv *, jobject);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    executeArg
 * Signature: ()Lmathlibra/NativeType;
 */
JNIEXPORT jobject JNICALL Java_mathlibra_Mathlibra_executeArg
  (JNIEnv *, jobject);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    getFunctionNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_mathlibra_Mathlibra_getFunctionNames
  (JNIEnv *, jobject);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    getFunctions
 * Signature: ()[Lmathlibra/FunctionData;
 */
JNIEXPORT jobjectArray JNICALL Java_mathlibra_Mathlibra_getFunctions
  (JNIEnv *, jobject);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    getVariableNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_mathlibra_Mathlibra_getVariableNames
  (JNIEnv *, jobject);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    getVariable
 * Signature: (Ljava/lang/String;)Lmathlibra/NativeType;
 */
JNIEXPORT jobject JNICALL Java_mathlibra_Mathlibra_getVariable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    setVariable
 * Signature: (Ljava/lang/String;Lmathlibra/NativeType;Z)V
 */
JNIEXPORT void JNICALL Java_mathlibra_Mathlibra_setVariable
  (JNIEnv *, jobject, jstring, jobject, jboolean);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    isVariableDefined
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mathlibra_Mathlibra_isVariableDefined
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    isVariableConst
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mathlibra_Mathlibra_isVariableConst
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    clearVariables
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mathlibra_Mathlibra_clearVariables
  (JNIEnv *, jobject);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    enablePlugins
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mathlibra_Mathlibra_enablePlugins
  (JNIEnv *, jobject);

/*
 * Class:     mathlibra_Mathlibra
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mathlibra_Mathlibra_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
