/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_rahmn_mathlibra_NativeType */

#ifndef _Included_net_rahmn_mathlibra_NativeType
#define _Included_net_rahmn_mathlibra_NativeType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    copyInstance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_rahmn_mathlibra_NativeType_copyInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    freeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_rahmn_mathlibra_NativeType_freeInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    sizeN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_rahmn_mathlibra_NativeType_sizeN
  (JNIEnv *, jobject);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    sizeM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_rahmn_mathlibra_NativeType_sizeM
  (JNIEnv *, jobject);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    isVector
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_rahmn_mathlibra_NativeType_isVector
  (JNIEnv *, jobject);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    isList
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_rahmn_mathlibra_NativeType_isList
  (JNIEnv *, jobject);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    isSingleton
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_rahmn_mathlibra_NativeType_isSingleton
  (JNIEnv *, jobject);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    isString
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_rahmn_mathlibra_NativeType_isString
  (JNIEnv *, jobject);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    isNumber
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_rahmn_mathlibra_NativeType_isNumber
  (JNIEnv *, jobject);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    makeType
 * Signature: ([DII)Lnet/rahmn/mathlibra/NativeType;
 */
JNIEXPORT jobject JNICALL Java_net_rahmn_mathlibra_NativeType_makeType___3DII
  (JNIEnv *, jclass, jdoubleArray, jint, jint);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    makeType
 * Signature: (Ljava/lang/String;)Lnet/rahmn/mathlibra/NativeType;
 */
JNIEXPORT jobject JNICALL Java_net_rahmn_mathlibra_NativeType_makeType__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    toNumberN
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_net_rahmn_mathlibra_NativeType_toNumberN
  (JNIEnv *, jobject);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_rahmn_mathlibra_NativeType_toString
  (JNIEnv *, jobject);

/*
 * Class:     net_rahmn_mathlibra_NativeType
 * Method:    getObj
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_net_rahmn_mathlibra_NativeType_getObj
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
